/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/kubesphere/kubeocean-api/apis/clusterapiproviderqc/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeQCClusterTemplates implements QCClusterTemplateInterface
type FakeQCClusterTemplates struct {
	Fake *FakeClusterapiproviderqcV1beta1
	ns   string
}

var qcclustertemplatesResource = schema.GroupVersionResource{Group: "clusterapiproviderqc", Version: "v1beta1", Resource: "qcclustertemplates"}

var qcclustertemplatesKind = schema.GroupVersionKind{Group: "clusterapiproviderqc", Version: "v1beta1", Kind: "QCClusterTemplate"}

// Get takes name of the qCClusterTemplate, and returns the corresponding qCClusterTemplate object, and an error if there is any.
func (c *FakeQCClusterTemplates) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.QCClusterTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(qcclustertemplatesResource, c.ns, name), &v1beta1.QCClusterTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.QCClusterTemplate), err
}

// List takes label and field selectors, and returns the list of QCClusterTemplates that match those selectors.
func (c *FakeQCClusterTemplates) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.QCClusterTemplateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(qcclustertemplatesResource, qcclustertemplatesKind, c.ns, opts), &v1beta1.QCClusterTemplateList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.QCClusterTemplateList{ListMeta: obj.(*v1beta1.QCClusterTemplateList).ListMeta}
	for _, item := range obj.(*v1beta1.QCClusterTemplateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested qCClusterTemplates.
func (c *FakeQCClusterTemplates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(qcclustertemplatesResource, c.ns, opts))

}

// Create takes the representation of a qCClusterTemplate and creates it.  Returns the server's representation of the qCClusterTemplate, and an error, if there is any.
func (c *FakeQCClusterTemplates) Create(ctx context.Context, qCClusterTemplate *v1beta1.QCClusterTemplate, opts v1.CreateOptions) (result *v1beta1.QCClusterTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(qcclustertemplatesResource, c.ns, qCClusterTemplate), &v1beta1.QCClusterTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.QCClusterTemplate), err
}

// Update takes the representation of a qCClusterTemplate and updates it. Returns the server's representation of the qCClusterTemplate, and an error, if there is any.
func (c *FakeQCClusterTemplates) Update(ctx context.Context, qCClusterTemplate *v1beta1.QCClusterTemplate, opts v1.UpdateOptions) (result *v1beta1.QCClusterTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(qcclustertemplatesResource, c.ns, qCClusterTemplate), &v1beta1.QCClusterTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.QCClusterTemplate), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeQCClusterTemplates) UpdateStatus(ctx context.Context, qCClusterTemplate *v1beta1.QCClusterTemplate, opts v1.UpdateOptions) (*v1beta1.QCClusterTemplate, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(qcclustertemplatesResource, "status", c.ns, qCClusterTemplate), &v1beta1.QCClusterTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.QCClusterTemplate), err
}

// Delete takes name of the qCClusterTemplate and deletes it. Returns an error if one occurs.
func (c *FakeQCClusterTemplates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(qcclustertemplatesResource, c.ns, name, opts), &v1beta1.QCClusterTemplate{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeQCClusterTemplates) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(qcclustertemplatesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.QCClusterTemplateList{})
	return err
}

// Patch applies the patch and returns the patched qCClusterTemplate.
func (c *FakeQCClusterTemplates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.QCClusterTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(qcclustertemplatesResource, c.ns, name, pt, data, subresources...), &v1beta1.QCClusterTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.QCClusterTemplate), err
}
