/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/kubesphere/kubeocean-api/apis/clusterapiproviderqc/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeQCClusters implements QCClusterInterface
type FakeQCClusters struct {
	Fake *FakeClusterapiproviderqcV1beta1
	ns   string
}

var qcclustersResource = schema.GroupVersionResource{Group: "clusterapiproviderqc", Version: "v1beta1", Resource: "qcclusters"}

var qcclustersKind = schema.GroupVersionKind{Group: "clusterapiproviderqc", Version: "v1beta1", Kind: "QCCluster"}

// Get takes name of the qCCluster, and returns the corresponding qCCluster object, and an error if there is any.
func (c *FakeQCClusters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.QCCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(qcclustersResource, c.ns, name), &v1beta1.QCCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.QCCluster), err
}

// List takes label and field selectors, and returns the list of QCClusters that match those selectors.
func (c *FakeQCClusters) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.QCClusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(qcclustersResource, qcclustersKind, c.ns, opts), &v1beta1.QCClusterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.QCClusterList{ListMeta: obj.(*v1beta1.QCClusterList).ListMeta}
	for _, item := range obj.(*v1beta1.QCClusterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested qCClusters.
func (c *FakeQCClusters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(qcclustersResource, c.ns, opts))

}

// Create takes the representation of a qCCluster and creates it.  Returns the server's representation of the qCCluster, and an error, if there is any.
func (c *FakeQCClusters) Create(ctx context.Context, qCCluster *v1beta1.QCCluster, opts v1.CreateOptions) (result *v1beta1.QCCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(qcclustersResource, c.ns, qCCluster), &v1beta1.QCCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.QCCluster), err
}

// Update takes the representation of a qCCluster and updates it. Returns the server's representation of the qCCluster, and an error, if there is any.
func (c *FakeQCClusters) Update(ctx context.Context, qCCluster *v1beta1.QCCluster, opts v1.UpdateOptions) (result *v1beta1.QCCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(qcclustersResource, c.ns, qCCluster), &v1beta1.QCCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.QCCluster), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeQCClusters) UpdateStatus(ctx context.Context, qCCluster *v1beta1.QCCluster, opts v1.UpdateOptions) (*v1beta1.QCCluster, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(qcclustersResource, "status", c.ns, qCCluster), &v1beta1.QCCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.QCCluster), err
}

// Delete takes name of the qCCluster and deletes it. Returns an error if one occurs.
func (c *FakeQCClusters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(qcclustersResource, c.ns, name, opts), &v1beta1.QCCluster{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeQCClusters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(qcclustersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.QCClusterList{})
	return err
}

// Patch applies the patch and returns the patched qCCluster.
func (c *FakeQCClusters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.QCCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(qcclustersResource, c.ns, name, pt, data, subresources...), &v1beta1.QCCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.QCCluster), err
}
