# permissions for end users to edit dolphinservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dolphinservice-editor-role
rules:
- apiGroups:
  - kubeocean.kubesphere.io
  resources:
  - dolphinservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeocean.kubesphere.io
  resources:
  - dolphinservices/status
  verbs:
  - get
