# permissions for end users to view dolphinservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dolphinservice-viewer-role
rules:
- apiGroups:
  - kubeocean.kubesphere.io
  resources:
  - dolphinservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubeocean.kubesphere.io
  resources:
  - dolphinservices/status
  verbs:
  - get
