# permissions for end users to edit kindclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kindcluster-editor-role
rules:
- apiGroups:
  - kubeocean.kubesphere.io
  resources:
  - kindclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeocean.kubesphere.io
  resources:
  - kindclusters/status
  verbs:
  - get
