# permissions for end users to view kindclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kindcluster-viewer-role
rules:
- apiGroups:
  - kubeocean.kubesphere.io
  resources:
  - kindclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubeocean.kubesphere.io
  resources:
  - kindclusters/status
  verbs:
  - get
