# permissions for end users to view kindclusterpools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kindclusterpool-viewer-role
rules:
- apiGroups:
  - kubeocean.kubesphere.io
  resources:
  - kindclusterpools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubeocean.kubesphere.io
  resources:
  - kindclusterpools/status
  verbs:
  - get
