# permissions for end users to edit myclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mycluster-editor-role
rules:
- apiGroups:
  - kubeocean.kubesphere.io.kubesphere.io
  resources:
  - myclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeocean.kubesphere.io.kubesphere.io
  resources:
  - myclusters/status
  verbs:
  - get
