# permissions for end users to view myclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mycluster-viewer-role
rules:
- apiGroups:
  - kubeocean.kubesphere.io.kubesphere.io
  resources:
  - myclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubeocean.kubesphere.io.kubesphere.io
  resources:
  - myclusters/status
  verbs:
  - get
