/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package versioned

import (
	"fmt"
	"net/http"

	bootstrapv1beta1 "github.com/kubesphere/kubeocean-api/client/clientset/versioned/typed/bootstrap/v1beta1"
	clusterapiv1beta1 "github.com/kubesphere/kubeocean-api/client/clientset/versioned/typed/clusterapi/v1beta1"
	clusterapiproviderqcv1beta1 "github.com/kubesphere/kubeocean-api/client/clientset/versioned/typed/clusterapiproviderqc/v1beta1"
	controlplanev1beta1 "github.com/kubesphere/kubeocean-api/client/clientset/versioned/typed/controlplane/v1beta1"
	kubeoceanv1alpha1 "github.com/kubesphere/kubeocean-api/client/clientset/versioned/typed/kubeocean/v1alpha1"
	discovery "k8s.io/client-go/discovery"
	rest "k8s.io/client-go/rest"
	flowcontrol "k8s.io/client-go/util/flowcontrol"
)

type Interface interface {
	Discovery() discovery.DiscoveryInterface
	BootstrapV1beta1() bootstrapv1beta1.BootstrapV1beta1Interface
	ClusterapiV1beta1() clusterapiv1beta1.ClusterapiV1beta1Interface
	ClusterapiproviderqcV1beta1() clusterapiproviderqcv1beta1.ClusterapiproviderqcV1beta1Interface
	ControlplaneV1beta1() controlplanev1beta1.ControlplaneV1beta1Interface
	KubeoceanV1alpha1() kubeoceanv1alpha1.KubeoceanV1alpha1Interface
}

// Clientset contains the clients for groups. Each group has exactly one
// version included in a Clientset.
type Clientset struct {
	*discovery.DiscoveryClient
	bootstrapV1beta1            *bootstrapv1beta1.BootstrapV1beta1Client
	clusterapiV1beta1           *clusterapiv1beta1.ClusterapiV1beta1Client
	clusterapiproviderqcV1beta1 *clusterapiproviderqcv1beta1.ClusterapiproviderqcV1beta1Client
	controlplaneV1beta1         *controlplanev1beta1.ControlplaneV1beta1Client
	kubeoceanV1alpha1           *kubeoceanv1alpha1.KubeoceanV1alpha1Client
}

// BootstrapV1beta1 retrieves the BootstrapV1beta1Client
func (c *Clientset) BootstrapV1beta1() bootstrapv1beta1.BootstrapV1beta1Interface {
	return c.bootstrapV1beta1
}

// ClusterapiV1beta1 retrieves the ClusterapiV1beta1Client
func (c *Clientset) ClusterapiV1beta1() clusterapiv1beta1.ClusterapiV1beta1Interface {
	return c.clusterapiV1beta1
}

// ClusterapiproviderqcV1beta1 retrieves the ClusterapiproviderqcV1beta1Client
func (c *Clientset) ClusterapiproviderqcV1beta1() clusterapiproviderqcv1beta1.ClusterapiproviderqcV1beta1Interface {
	return c.clusterapiproviderqcV1beta1
}

// ControlplaneV1beta1 retrieves the ControlplaneV1beta1Client
func (c *Clientset) ControlplaneV1beta1() controlplanev1beta1.ControlplaneV1beta1Interface {
	return c.controlplaneV1beta1
}

// KubeoceanV1alpha1 retrieves the KubeoceanV1alpha1Client
func (c *Clientset) KubeoceanV1alpha1() kubeoceanv1alpha1.KubeoceanV1alpha1Interface {
	return c.kubeoceanV1alpha1
}

// Discovery retrieves the DiscoveryClient
func (c *Clientset) Discovery() discovery.DiscoveryInterface {
	if c == nil {
		return nil
	}
	return c.DiscoveryClient
}

// NewForConfig creates a new Clientset for the given config.
// If config's RateLimiter is not set and QPS and Burst are acceptable,
// NewForConfig will generate a rate-limiter in configShallowCopy.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*Clientset, error) {
	configShallowCopy := *c

	// share the transport between all clients
	httpClient, err := rest.HTTPClientFor(&configShallowCopy)
	if err != nil {
		return nil, err
	}

	return NewForConfigAndClient(&configShallowCopy, httpClient)
}

// NewForConfigAndClient creates a new Clientset for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
// If config's RateLimiter is not set and QPS and Burst are acceptable,
// NewForConfigAndClient will generate a rate-limiter in configShallowCopy.
func NewForConfigAndClient(c *rest.Config, httpClient *http.Client) (*Clientset, error) {
	configShallowCopy := *c
	if configShallowCopy.RateLimiter == nil && configShallowCopy.QPS > 0 {
		if configShallowCopy.Burst <= 0 {
			return nil, fmt.Errorf("burst is required to be greater than 0 when RateLimiter is not set and QPS is set to greater than 0")
		}
		configShallowCopy.RateLimiter = flowcontrol.NewTokenBucketRateLimiter(configShallowCopy.QPS, configShallowCopy.Burst)
	}

	var cs Clientset
	var err error
	cs.bootstrapV1beta1, err = bootstrapv1beta1.NewForConfigAndClient(&configShallowCopy, httpClient)
	if err != nil {
		return nil, err
	}
	cs.clusterapiV1beta1, err = clusterapiv1beta1.NewForConfigAndClient(&configShallowCopy, httpClient)
	if err != nil {
		return nil, err
	}
	cs.clusterapiproviderqcV1beta1, err = clusterapiproviderqcv1beta1.NewForConfigAndClient(&configShallowCopy, httpClient)
	if err != nil {
		return nil, err
	}
	cs.controlplaneV1beta1, err = controlplanev1beta1.NewForConfigAndClient(&configShallowCopy, httpClient)
	if err != nil {
		return nil, err
	}
	cs.kubeoceanV1alpha1, err = kubeoceanv1alpha1.NewForConfigAndClient(&configShallowCopy, httpClient)
	if err != nil {
		return nil, err
	}

	cs.DiscoveryClient, err = discovery.NewDiscoveryClientForConfigAndClient(&configShallowCopy, httpClient)
	if err != nil {
		return nil, err
	}
	return &cs, nil
}

// NewForConfigOrDie creates a new Clientset for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *Clientset {
	cs, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return cs
}

// New creates a new Clientset for the given RESTClient.
func New(c rest.Interface) *Clientset {
	var cs Clientset
	cs.bootstrapV1beta1 = bootstrapv1beta1.New(c)
	cs.clusterapiV1beta1 = clusterapiv1beta1.New(c)
	cs.clusterapiproviderqcV1beta1 = clusterapiproviderqcv1beta1.New(c)
	cs.controlplaneV1beta1 = controlplanev1beta1.New(c)
	cs.kubeoceanV1alpha1 = kubeoceanv1alpha1.New(c)

	cs.DiscoveryClient = discovery.NewDiscoveryClient(c)
	return &cs
}
