/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// QCClusterListerExpansion allows custom methods to be added to
// QCClusterLister.
type QCClusterListerExpansion interface{}

// QCClusterNamespaceListerExpansion allows custom methods to be added to
// QCClusterNamespaceLister.
type QCClusterNamespaceListerExpansion interface{}

// QCClusterTemplateListerExpansion allows custom methods to be added to
// QCClusterTemplateLister.
type QCClusterTemplateListerExpansion interface{}

// QCClusterTemplateNamespaceListerExpansion allows custom methods to be added to
// QCClusterTemplateNamespaceLister.
type QCClusterTemplateNamespaceListerExpansion interface{}

// QCMachineListerExpansion allows custom methods to be added to
// QCMachineLister.
type QCMachineListerExpansion interface{}

// QCMachineNamespaceListerExpansion allows custom methods to be added to
// QCMachineNamespaceLister.
type QCMachineNamespaceListerExpansion interface{}

// QCMachineTemplateListerExpansion allows custom methods to be added to
// QCMachineTemplateLister.
type QCMachineTemplateListerExpansion interface{}

// QCMachineTemplateNamespaceListerExpansion allows custom methods to be added to
// QCMachineTemplateNamespaceLister.
type QCMachineTemplateNamespaceListerExpansion interface{}
