// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneSpecification) DeepCopyInto(out *ControlPlaneSpecification) {
	*out = *in
	if in.CpuCurrent != nil {
		in, out := &in.CpuCurrent, &out.CpuCurrent
		*out = new(int32)
		**out = **in
	}
	if in.MemoryCurrent != nil {
		in, out := &in.MemoryCurrent, &out.MemoryCurrent
		*out = new(int32)
		**out = **in
	}
	if in.DiskSize != nil {
		in, out := &in.DiskSize, &out.DiskSize
		*out = new(int32)
		**out = **in
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneSpecification.
func (in *ControlPlaneSpecification) DeepCopy() *ControlPlaneSpecification {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneSpecification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DolphinCluster) DeepCopyInto(out *DolphinCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DolphinCluster.
func (in *DolphinCluster) DeepCopy() *DolphinCluster {
	if in == nil {
		return nil
	}
	out := new(DolphinCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DolphinCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DolphinClusterList) DeepCopyInto(out *DolphinClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DolphinCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DolphinClusterList.
func (in *DolphinClusterList) DeepCopy() *DolphinClusterList {
	if in == nil {
		return nil
	}
	out := new(DolphinClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DolphinClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DolphinClusterSpec) DeepCopyInto(out *DolphinClusterSpec) {
	*out = *in
	in.VirtualCluster.DeepCopyInto(&out.VirtualCluster)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DolphinClusterSpec.
func (in *DolphinClusterSpec) DeepCopy() *DolphinClusterSpec {
	if in == nil {
		return nil
	}
	out := new(DolphinClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DolphinClusterStatus) DeepCopyInto(out *DolphinClusterStatus) {
	*out = *in
	in.InitNode.DeepCopyInto(&out.InitNode)
	if in.Specifications != nil {
		in, out := &in.Specifications, &out.Specifications
		*out = make([]VirtualClusterNodeSpecificationStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Kubesphere = in.Kubesphere
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DolphinClusterStatus.
func (in *DolphinClusterStatus) DeepCopy() *DolphinClusterStatus {
	if in == nil {
		return nil
	}
	out := new(DolphinClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DolphinService) DeepCopyInto(out *DolphinService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DolphinService.
func (in *DolphinService) DeepCopy() *DolphinService {
	if in == nil {
		return nil
	}
	out := new(DolphinService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DolphinService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DolphinServiceList) DeepCopyInto(out *DolphinServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DolphinService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DolphinServiceList.
func (in *DolphinServiceList) DeepCopy() *DolphinServiceList {
	if in == nil {
		return nil
	}
	out := new(DolphinServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DolphinServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DolphinServiceSpec) DeepCopyInto(out *DolphinServiceSpec) {
	*out = *in
	out.Service = in.Service
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DolphinServiceSpec.
func (in *DolphinServiceSpec) DeepCopy() *DolphinServiceSpec {
	if in == nil {
		return nil
	}
	out := new(DolphinServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DolphinServiceStatus) DeepCopyInto(out *DolphinServiceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DolphinServiceStatus.
func (in *DolphinServiceStatus) DeepCopy() *DolphinServiceStatus {
	if in == nil {
		return nil
	}
	out := new(DolphinServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageRepoVersion) DeepCopyInto(out *ImageRepoVersion) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageRepoVersion.
func (in *ImageRepoVersion) DeepCopy() *ImageRepoVersion {
	if in == nil {
		return nil
	}
	out := new(ImageRepoVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kubesphere) DeepCopyInto(out *Kubesphere) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kubesphere.
func (in *Kubesphere) DeepCopy() *Kubesphere {
	if in == nil {
		return nil
	}
	out := new(Kubesphere)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubesphereStatus) DeepCopyInto(out *KubesphereStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubesphereStatus.
func (in *KubesphereStatus) DeepCopy() *KubesphereStatus {
	if in == nil {
		return nil
	}
	out := new(KubesphereStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Service) DeepCopyInto(out *Service) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Service.
func (in *Service) DeepCopy() *Service {
	if in == nil {
		return nil
	}
	out := new(Service)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Specification) DeepCopyInto(out *Specification) {
	*out = *in
	if in.WaitToAssignVirtualClusterThreshold != nil {
		in, out := &in.WaitToAssignVirtualClusterThreshold, &out.WaitToAssignVirtualClusterThreshold
		*out = new(int32)
		**out = **in
	}
	if in.WaitToAssignKubesphereInstalledVirtualClusterThreshold != nil {
		in, out := &in.WaitToAssignKubesphereInstalledVirtualClusterThreshold, &out.WaitToAssignKubesphereInstalledVirtualClusterThreshold
		*out = new(int32)
		**out = **in
	}
	if in.WaitToConvertWorkerNodeThreshold != nil {
		in, out := &in.WaitToConvertWorkerNodeThreshold, &out.WaitToConvertWorkerNodeThreshold
		*out = new(int32)
		**out = **in
	}
	if in.CpuCurrent != nil {
		in, out := &in.CpuCurrent, &out.CpuCurrent
		*out = new(int32)
		**out = **in
	}
	if in.MemoryCurrent != nil {
		in, out := &in.MemoryCurrent, &out.MemoryCurrent
		*out = new(int32)
		**out = **in
	}
	if in.DiskSize != nil {
		in, out := &in.DiskSize, &out.DiskSize
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Specification.
func (in *Specification) DeepCopy() *Specification {
	if in == nil {
		return nil
	}
	out := new(Specification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualCluster) DeepCopyInto(out *VirtualCluster) {
	*out = *in
	in.K3s.DeepCopyInto(&out.K3s)
	in.Vcluster.DeepCopyInto(&out.Vcluster)
	in.Plugins.DeepCopyInto(&out.Plugins)
	in.InitNode.DeepCopyInto(&out.InitNode)
	if in.Specifications != nil {
		in, out := &in.Specifications, &out.Specifications
		*out = make([]VirtualClusterNodeSpecification, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Kubesphere = in.Kubesphere
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualCluster.
func (in *VirtualCluster) DeepCopy() *VirtualCluster {
	if in == nil {
		return nil
	}
	out := new(VirtualCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualClusterInitNodeSpecification) DeepCopyInto(out *VirtualClusterInitNodeSpecification) {
	*out = *in
	in.VirtualClusterNode.DeepCopyInto(&out.VirtualClusterNode)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualClusterInitNodeSpecification.
func (in *VirtualClusterInitNodeSpecification) DeepCopy() *VirtualClusterInitNodeSpecification {
	if in == nil {
		return nil
	}
	out := new(VirtualClusterInitNodeSpecification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualClusterNode) DeepCopyInto(out *VirtualClusterNode) {
	*out = *in
	if in.CpuCurrent != nil {
		in, out := &in.CpuCurrent, &out.CpuCurrent
		*out = new(int32)
		**out = **in
	}
	if in.MemoryCurrent != nil {
		in, out := &in.MemoryCurrent, &out.MemoryCurrent
		*out = new(int32)
		**out = **in
	}
	if in.DiskSize != nil {
		in, out := &in.DiskSize, &out.DiskSize
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualClusterNode.
func (in *VirtualClusterNode) DeepCopy() *VirtualClusterNode {
	if in == nil {
		return nil
	}
	out := new(VirtualClusterNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualClusterNodeSpecification) DeepCopyInto(out *VirtualClusterNodeSpecification) {
	*out = *in
	in.VirtualClusterNode.DeepCopyInto(&out.VirtualClusterNode)
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualClusterNodeSpecification.
func (in *VirtualClusterNodeSpecification) DeepCopy() *VirtualClusterNodeSpecification {
	if in == nil {
		return nil
	}
	out := new(VirtualClusterNodeSpecification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualClusterNodeSpecificationStatus) DeepCopyInto(out *VirtualClusterNodeSpecificationStatus) {
	*out = *in
	in.VirtualClusterNode.DeepCopyInto(&out.VirtualClusterNode)
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualClusterNodeSpecificationStatus.
func (in *VirtualClusterNodeSpecificationStatus) DeepCopy() *VirtualClusterNodeSpecificationStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualClusterNodeSpecificationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualClusterPool) DeepCopyInto(out *VirtualClusterPool) {
	*out = *in
	if in.NotAssigned != nil {
		in, out := &in.NotAssigned, &out.NotAssigned
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualClusterPool.
func (in *VirtualClusterPool) DeepCopy() *VirtualClusterPool {
	if in == nil {
		return nil
	}
	out := new(VirtualClusterPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualClusterSpecification) DeepCopyInto(out *VirtualClusterSpecification) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualClusterSpecification.
func (in *VirtualClusterSpecification) DeepCopy() *VirtualClusterSpecification {
	if in == nil {
		return nil
	}
	out := new(VirtualClusterSpecification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualClusterSpecification) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualClusterSpecificationList) DeepCopyInto(out *VirtualClusterSpecificationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualClusterSpecification, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualClusterSpecificationList.
func (in *VirtualClusterSpecificationList) DeepCopy() *VirtualClusterSpecificationList {
	if in == nil {
		return nil
	}
	out := new(VirtualClusterSpecificationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualClusterSpecificationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualClusterSpecificationSpec) DeepCopyInto(out *VirtualClusterSpecificationSpec) {
	*out = *in
	in.ControlPlaneSpecification.DeepCopyInto(&out.ControlPlaneSpecification)
	if in.Specifications != nil {
		in, out := &in.Specifications, &out.Specifications
		*out = make([]Specification, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ClusterMaxNodeCount != nil {
		in, out := &in.ClusterMaxNodeCount, &out.ClusterMaxNodeCount
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualClusterSpecificationSpec.
func (in *VirtualClusterSpecificationSpec) DeepCopy() *VirtualClusterSpecificationSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualClusterSpecificationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualClusterSpecificationStatus) DeepCopyInto(out *VirtualClusterSpecificationStatus) {
	*out = *in
	if in.VirtualClusterPool != nil {
		in, out := &in.VirtualClusterPool, &out.VirtualClusterPool
		*out = make([]VirtualClusterPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.KubesphereInstalledVirtualClusterPool != nil {
		in, out := &in.KubesphereInstalledVirtualClusterPool, &out.KubesphereInstalledVirtualClusterPool
		*out = make([]VirtualClusterPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.WorkerNodePool != nil {
		in, out := &in.WorkerNodePool, &out.WorkerNodePool
		*out = make([]WorkerNodePool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualClusterSpecificationStatus.
func (in *VirtualClusterSpecificationStatus) DeepCopy() *VirtualClusterSpecificationStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualClusterSpecificationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerNodePool) DeepCopyInto(out *WorkerNodePool) {
	*out = *in
	if in.Converted != nil {
		in, out := &in.Converted, &out.Converted
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NotConverted != nil {
		in, out := &in.NotConverted, &out.NotConverted
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerNodePool.
func (in *WorkerNodePool) DeepCopy() *WorkerNodePool {
	if in == nil {
		return nil
	}
	out := new(WorkerNodePool)
	in.DeepCopyInto(out)
	return out
}
