// +build !ignore_autogenerated

/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneSpecification) DeepCopyInto(out *ControlPlaneSpecification) {
	*out = *in
	if in.CpuCurrent != nil {
		in, out := &in.CpuCurrent, &out.CpuCurrent
		*out = new(int32)
		**out = **in
	}
	if in.MemoryCurrent != nil {
		in, out := &in.MemoryCurrent, &out.MemoryCurrent
		*out = new(int32)
		**out = **in
	}
	if in.DiskSize != nil {
		in, out := &in.DiskSize, &out.DiskSize
		*out = new(int32)
		**out = **in
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneSpecification.
func (in *ControlPlaneSpecification) DeepCopy() *ControlPlaneSpecification {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneSpecification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DolphinCluster) DeepCopyInto(out *DolphinCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DolphinCluster.
func (in *DolphinCluster) DeepCopy() *DolphinCluster {
	if in == nil {
		return nil
	}
	out := new(DolphinCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DolphinCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DolphinClusterList) DeepCopyInto(out *DolphinClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DolphinCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DolphinClusterList.
func (in *DolphinClusterList) DeepCopy() *DolphinClusterList {
	if in == nil {
		return nil
	}
	out := new(DolphinClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DolphinClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in DolphinClusterPool) DeepCopyInto(out *DolphinClusterPool) {
	{
		in := &in
		*out = make(DolphinClusterPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DolphinClusterPool.
func (in DolphinClusterPool) DeepCopy() DolphinClusterPool {
	if in == nil {
		return nil
	}
	out := new(DolphinClusterPool)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DolphinClusterPoolItem) DeepCopyInto(out *DolphinClusterPoolItem) {
	*out = *in
	if in.NotAssigned != nil {
		in, out := &in.NotAssigned, &out.NotAssigned
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DolphinClusterPoolItem.
func (in *DolphinClusterPoolItem) DeepCopy() *DolphinClusterPoolItem {
	if in == nil {
		return nil
	}
	out := new(DolphinClusterPoolItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DolphinClusterSpec) DeepCopyInto(out *DolphinClusterSpec) {
	*out = *in
	in.VirtualCluster.DeepCopyInto(&out.VirtualCluster)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DolphinClusterSpec.
func (in *DolphinClusterSpec) DeepCopy() *DolphinClusterSpec {
	if in == nil {
		return nil
	}
	out := new(DolphinClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DolphinClusterSpecification) DeepCopyInto(out *DolphinClusterSpecification) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DolphinClusterSpecification.
func (in *DolphinClusterSpecification) DeepCopy() *DolphinClusterSpecification {
	if in == nil {
		return nil
	}
	out := new(DolphinClusterSpecification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DolphinClusterSpecification) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DolphinClusterSpecificationList) DeepCopyInto(out *DolphinClusterSpecificationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DolphinClusterSpecification, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DolphinClusterSpecificationList.
func (in *DolphinClusterSpecificationList) DeepCopy() *DolphinClusterSpecificationList {
	if in == nil {
		return nil
	}
	out := new(DolphinClusterSpecificationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DolphinClusterSpecificationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DolphinClusterSpecificationSpec) DeepCopyInto(out *DolphinClusterSpecificationSpec) {
	*out = *in
	in.ControlPlaneSpecification.DeepCopyInto(&out.ControlPlaneSpecification)
	if in.Specifications != nil {
		in, out := &in.Specifications, &out.Specifications
		*out = make([]Specification, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ClusterMaxWorkerNodeCount != nil {
		in, out := &in.ClusterMaxWorkerNodeCount, &out.ClusterMaxWorkerNodeCount
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DolphinClusterSpecificationSpec.
func (in *DolphinClusterSpecificationSpec) DeepCopy() *DolphinClusterSpecificationSpec {
	if in == nil {
		return nil
	}
	out := new(DolphinClusterSpecificationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DolphinClusterSpecificationStatus) DeepCopyInto(out *DolphinClusterSpecificationStatus) {
	*out = *in
	if in.WorkerNodePool != nil {
		in, out := &in.WorkerNodePool, &out.WorkerNodePool
		*out = make(WorkerNodePool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DolphinClusterPool != nil {
		in, out := &in.DolphinClusterPool, &out.DolphinClusterPool
		*out = make(DolphinClusterPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.KubesphereInstalledDolphinClusterPool != nil {
		in, out := &in.KubesphereInstalledDolphinClusterPool, &out.KubesphereInstalledDolphinClusterPool
		*out = make(KsInstalledDolphinClusterPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DolphinClusterSpecificationStatus.
func (in *DolphinClusterSpecificationStatus) DeepCopy() *DolphinClusterSpecificationStatus {
	if in == nil {
		return nil
	}
	out := new(DolphinClusterSpecificationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DolphinClusterStatus) DeepCopyInto(out *DolphinClusterStatus) {
	*out = *in
	in.InitNode.DeepCopyInto(&out.InitNode)
	if in.Specifications != nil {
		in, out := &in.Specifications, &out.Specifications
		*out = make([]VirtualClusterNodeSpecificationStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Kubesphere = in.Kubesphere
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DolphinClusterStatus.
func (in *DolphinClusterStatus) DeepCopy() *DolphinClusterStatus {
	if in == nil {
		return nil
	}
	out := new(DolphinClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DolphinService) DeepCopyInto(out *DolphinService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DolphinService.
func (in *DolphinService) DeepCopy() *DolphinService {
	if in == nil {
		return nil
	}
	out := new(DolphinService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DolphinService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DolphinServiceList) DeepCopyInto(out *DolphinServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DolphinService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DolphinServiceList.
func (in *DolphinServiceList) DeepCopy() *DolphinServiceList {
	if in == nil {
		return nil
	}
	out := new(DolphinServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DolphinServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DolphinServiceSpec) DeepCopyInto(out *DolphinServiceSpec) {
	*out = *in
	out.Service = in.Service
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DolphinServiceSpec.
func (in *DolphinServiceSpec) DeepCopy() *DolphinServiceSpec {
	if in == nil {
		return nil
	}
	out := new(DolphinServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DolphinServiceStatus) DeepCopyInto(out *DolphinServiceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DolphinServiceStatus.
func (in *DolphinServiceStatus) DeepCopy() *DolphinServiceStatus {
	if in == nil {
		return nil
	}
	out := new(DolphinServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageRepoVersion) DeepCopyInto(out *ImageRepoVersion) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageRepoVersion.
func (in *ImageRepoVersion) DeepCopy() *ImageRepoVersion {
	if in == nil {
		return nil
	}
	out := new(ImageRepoVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in KsInstalledDolphinClusterPool) DeepCopyInto(out *KsInstalledDolphinClusterPool) {
	{
		in := &in
		*out = make(KsInstalledDolphinClusterPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KsInstalledDolphinClusterPool.
func (in KsInstalledDolphinClusterPool) DeepCopy() KsInstalledDolphinClusterPool {
	if in == nil {
		return nil
	}
	out := new(KsInstalledDolphinClusterPool)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KsInstalledDolphinClusterPoolItem) DeepCopyInto(out *KsInstalledDolphinClusterPoolItem) {
	*out = *in
	if in.NotAssigned != nil {
		in, out := &in.NotAssigned, &out.NotAssigned
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KsInstalledDolphinClusterPoolItem.
func (in *KsInstalledDolphinClusterPoolItem) DeepCopy() *KsInstalledDolphinClusterPoolItem {
	if in == nil {
		return nil
	}
	out := new(KsInstalledDolphinClusterPoolItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kubesphere) DeepCopyInto(out *Kubesphere) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kubesphere.
func (in *Kubesphere) DeepCopy() *Kubesphere {
	if in == nil {
		return nil
	}
	out := new(Kubesphere)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubesphereStatus) DeepCopyInto(out *KubesphereStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubesphereStatus.
func (in *KubesphereStatus) DeepCopy() *KubesphereStatus {
	if in == nil {
		return nil
	}
	out := new(KubesphereStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Service) DeepCopyInto(out *Service) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Service.
func (in *Service) DeepCopy() *Service {
	if in == nil {
		return nil
	}
	out := new(Service)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Specification) DeepCopyInto(out *Specification) {
	*out = *in
	if in.WaitToAssignDolphinClusterThreshold != nil {
		in, out := &in.WaitToAssignDolphinClusterThreshold, &out.WaitToAssignDolphinClusterThreshold
		*out = new(int32)
		**out = **in
	}
	if in.WaitToAssignKubesphereInstalledDolphinClusterThreshold != nil {
		in, out := &in.WaitToAssignKubesphereInstalledDolphinClusterThreshold, &out.WaitToAssignKubesphereInstalledDolphinClusterThreshold
		*out = new(int32)
		**out = **in
	}
	if in.WaitToConvertWorkerNodeThreshold != nil {
		in, out := &in.WaitToConvertWorkerNodeThreshold, &out.WaitToConvertWorkerNodeThreshold
		*out = new(int32)
		**out = **in
	}
	if in.CpuCurrent != nil {
		in, out := &in.CpuCurrent, &out.CpuCurrent
		*out = new(int32)
		**out = **in
	}
	if in.MemoryCurrent != nil {
		in, out := &in.MemoryCurrent, &out.MemoryCurrent
		*out = new(int32)
		**out = **in
	}
	if in.DiskSize != nil {
		in, out := &in.DiskSize, &out.DiskSize
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Specification.
func (in *Specification) DeepCopy() *Specification {
	if in == nil {
		return nil
	}
	out := new(Specification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualCluster) DeepCopyInto(out *VirtualCluster) {
	*out = *in
	in.K3s.DeepCopyInto(&out.K3s)
	in.Vcluster.DeepCopyInto(&out.Vcluster)
	in.Plugins.DeepCopyInto(&out.Plugins)
	in.InitNode.DeepCopyInto(&out.InitNode)
	if in.Specifications != nil {
		in, out := &in.Specifications, &out.Specifications
		*out = make([]VirtualClusterNodeSpecification, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Kubesphere = in.Kubesphere
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualCluster.
func (in *VirtualCluster) DeepCopy() *VirtualCluster {
	if in == nil {
		return nil
	}
	out := new(VirtualCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualClusterInitNodeSpecification) DeepCopyInto(out *VirtualClusterInitNodeSpecification) {
	*out = *in
	in.VirtualClusterNode.DeepCopyInto(&out.VirtualClusterNode)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualClusterInitNodeSpecification.
func (in *VirtualClusterInitNodeSpecification) DeepCopy() *VirtualClusterInitNodeSpecification {
	if in == nil {
		return nil
	}
	out := new(VirtualClusterInitNodeSpecification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualClusterNode) DeepCopyInto(out *VirtualClusterNode) {
	*out = *in
	if in.CpuCurrent != nil {
		in, out := &in.CpuCurrent, &out.CpuCurrent
		*out = new(int32)
		**out = **in
	}
	if in.MemoryCurrent != nil {
		in, out := &in.MemoryCurrent, &out.MemoryCurrent
		*out = new(int32)
		**out = **in
	}
	if in.DiskSize != nil {
		in, out := &in.DiskSize, &out.DiskSize
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualClusterNode.
func (in *VirtualClusterNode) DeepCopy() *VirtualClusterNode {
	if in == nil {
		return nil
	}
	out := new(VirtualClusterNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualClusterNodeSpecification) DeepCopyInto(out *VirtualClusterNodeSpecification) {
	*out = *in
	in.VirtualClusterNode.DeepCopyInto(&out.VirtualClusterNode)
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualClusterNodeSpecification.
func (in *VirtualClusterNodeSpecification) DeepCopy() *VirtualClusterNodeSpecification {
	if in == nil {
		return nil
	}
	out := new(VirtualClusterNodeSpecification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualClusterNodeSpecificationStatus) DeepCopyInto(out *VirtualClusterNodeSpecificationStatus) {
	*out = *in
	in.VirtualClusterNode.DeepCopyInto(&out.VirtualClusterNode)
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualClusterNodeSpecificationStatus.
func (in *VirtualClusterNodeSpecificationStatus) DeepCopy() *VirtualClusterNodeSpecificationStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualClusterNodeSpecificationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in WorkerNodePool) DeepCopyInto(out *WorkerNodePool) {
	{
		in := &in
		*out = make(WorkerNodePool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerNodePool.
func (in WorkerNodePool) DeepCopy() WorkerNodePool {
	if in == nil {
		return nil
	}
	out := new(WorkerNodePool)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerNodePoolItem) DeepCopyInto(out *WorkerNodePoolItem) {
	*out = *in
	if in.Converted != nil {
		in, out := &in.Converted, &out.Converted
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NotConverted != nil {
		in, out := &in.NotConverted, &out.NotConverted
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerNodePoolItem.
func (in *WorkerNodePoolItem) DeepCopy() *WorkerNodePoolItem {
	if in == nil {
		return nil
	}
	out := new(WorkerNodePoolItem)
	in.DeepCopyInto(out)
	return out
}
