/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v2alpha1 "github.com/kubesphere/kubeocean-api/v2/apis/kubeocean/v2alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeExposedServices implements ExposedServiceInterface
type FakeExposedServices struct {
	Fake *FakeKubeoceanV2alpha1
	ns   string
}

var exposedservicesResource = schema.GroupVersionResource{Group: "kubeocean.kubesphere.io", Version: "v2alpha1", Resource: "exposedservices"}

var exposedservicesKind = schema.GroupVersionKind{Group: "kubeocean.kubesphere.io", Version: "v2alpha1", Kind: "ExposedService"}

// Get takes name of the exposedService, and returns the corresponding exposedService object, and an error if there is any.
func (c *FakeExposedServices) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2alpha1.ExposedService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(exposedservicesResource, c.ns, name), &v2alpha1.ExposedService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.ExposedService), err
}

// List takes label and field selectors, and returns the list of ExposedServices that match those selectors.
func (c *FakeExposedServices) List(ctx context.Context, opts v1.ListOptions) (result *v2alpha1.ExposedServiceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(exposedservicesResource, exposedservicesKind, c.ns, opts), &v2alpha1.ExposedServiceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v2alpha1.ExposedServiceList{ListMeta: obj.(*v2alpha1.ExposedServiceList).ListMeta}
	for _, item := range obj.(*v2alpha1.ExposedServiceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested exposedServices.
func (c *FakeExposedServices) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(exposedservicesResource, c.ns, opts))

}

// Create takes the representation of a exposedService and creates it.  Returns the server's representation of the exposedService, and an error, if there is any.
func (c *FakeExposedServices) Create(ctx context.Context, exposedService *v2alpha1.ExposedService, opts v1.CreateOptions) (result *v2alpha1.ExposedService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(exposedservicesResource, c.ns, exposedService), &v2alpha1.ExposedService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.ExposedService), err
}

// Update takes the representation of a exposedService and updates it. Returns the server's representation of the exposedService, and an error, if there is any.
func (c *FakeExposedServices) Update(ctx context.Context, exposedService *v2alpha1.ExposedService, opts v1.UpdateOptions) (result *v2alpha1.ExposedService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(exposedservicesResource, c.ns, exposedService), &v2alpha1.ExposedService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.ExposedService), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeExposedServices) UpdateStatus(ctx context.Context, exposedService *v2alpha1.ExposedService, opts v1.UpdateOptions) (*v2alpha1.ExposedService, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(exposedservicesResource, "status", c.ns, exposedService), &v2alpha1.ExposedService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.ExposedService), err
}

// Delete takes name of the exposedService and deletes it. Returns an error if one occurs.
func (c *FakeExposedServices) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(exposedservicesResource, c.ns, name, opts), &v2alpha1.ExposedService{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeExposedServices) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(exposedservicesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v2alpha1.ExposedServiceList{})
	return err
}

// Patch applies the patch and returns the patched exposedService.
func (c *FakeExposedServices) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.ExposedService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(exposedservicesResource, c.ns, name, pt, data, subresources...), &v2alpha1.ExposedService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.ExposedService), err
}
