/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v2alpha1 "github.com/kubesphere/kubeocean-api/v2/apis/kubeocean/v2alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKindClusterPools implements KindClusterPoolInterface
type FakeKindClusterPools struct {
	Fake *FakeKubeoceanV2alpha1
}

var kindclusterpoolsResource = schema.GroupVersionResource{Group: "kubeocean.kubesphere.io", Version: "v2alpha1", Resource: "kindclusterpools"}

var kindclusterpoolsKind = schema.GroupVersionKind{Group: "kubeocean.kubesphere.io", Version: "v2alpha1", Kind: "KindClusterPool"}

// Get takes name of the kindClusterPool, and returns the corresponding kindClusterPool object, and an error if there is any.
func (c *FakeKindClusterPools) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2alpha1.KindClusterPool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(kindclusterpoolsResource, name), &v2alpha1.KindClusterPool{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.KindClusterPool), err
}

// List takes label and field selectors, and returns the list of KindClusterPools that match those selectors.
func (c *FakeKindClusterPools) List(ctx context.Context, opts v1.ListOptions) (result *v2alpha1.KindClusterPoolList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(kindclusterpoolsResource, kindclusterpoolsKind, opts), &v2alpha1.KindClusterPoolList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v2alpha1.KindClusterPoolList{ListMeta: obj.(*v2alpha1.KindClusterPoolList).ListMeta}
	for _, item := range obj.(*v2alpha1.KindClusterPoolList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kindClusterPools.
func (c *FakeKindClusterPools) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(kindclusterpoolsResource, opts))
}

// Create takes the representation of a kindClusterPool and creates it.  Returns the server's representation of the kindClusterPool, and an error, if there is any.
func (c *FakeKindClusterPools) Create(ctx context.Context, kindClusterPool *v2alpha1.KindClusterPool, opts v1.CreateOptions) (result *v2alpha1.KindClusterPool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(kindclusterpoolsResource, kindClusterPool), &v2alpha1.KindClusterPool{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.KindClusterPool), err
}

// Update takes the representation of a kindClusterPool and updates it. Returns the server's representation of the kindClusterPool, and an error, if there is any.
func (c *FakeKindClusterPools) Update(ctx context.Context, kindClusterPool *v2alpha1.KindClusterPool, opts v1.UpdateOptions) (result *v2alpha1.KindClusterPool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(kindclusterpoolsResource, kindClusterPool), &v2alpha1.KindClusterPool{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.KindClusterPool), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKindClusterPools) UpdateStatus(ctx context.Context, kindClusterPool *v2alpha1.KindClusterPool, opts v1.UpdateOptions) (*v2alpha1.KindClusterPool, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(kindclusterpoolsResource, "status", kindClusterPool), &v2alpha1.KindClusterPool{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.KindClusterPool), err
}

// Delete takes name of the kindClusterPool and deletes it. Returns an error if one occurs.
func (c *FakeKindClusterPools) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(kindclusterpoolsResource, name, opts), &v2alpha1.KindClusterPool{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKindClusterPools) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(kindclusterpoolsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v2alpha1.KindClusterPoolList{})
	return err
}

// Patch applies the patch and returns the patched kindClusterPool.
func (c *FakeKindClusterPools) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.KindClusterPool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(kindclusterpoolsResource, name, pt, data, subresources...), &v2alpha1.KindClusterPool{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.KindClusterPool), err
}
