/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kubesphere/kubeocean-api/apis/kubeocean/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDolphinClusters implements DolphinClusterInterface
type FakeDolphinClusters struct {
	Fake *FakeKubeoceanV1alpha1
}

var dolphinclustersResource = schema.GroupVersionResource{Group: "kubeocean.kubesphere.io", Version: "v1alpha1", Resource: "dolphinclusters"}

var dolphinclustersKind = schema.GroupVersionKind{Group: "kubeocean.kubesphere.io", Version: "v1alpha1", Kind: "DolphinCluster"}

// Get takes name of the dolphinCluster, and returns the corresponding dolphinCluster object, and an error if there is any.
func (c *FakeDolphinClusters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DolphinCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(dolphinclustersResource, name), &v1alpha1.DolphinCluster{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DolphinCluster), err
}

// List takes label and field selectors, and returns the list of DolphinClusters that match those selectors.
func (c *FakeDolphinClusters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DolphinClusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(dolphinclustersResource, dolphinclustersKind, opts), &v1alpha1.DolphinClusterList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DolphinClusterList{ListMeta: obj.(*v1alpha1.DolphinClusterList).ListMeta}
	for _, item := range obj.(*v1alpha1.DolphinClusterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dolphinClusters.
func (c *FakeDolphinClusters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(dolphinclustersResource, opts))
}

// Create takes the representation of a dolphinCluster and creates it.  Returns the server's representation of the dolphinCluster, and an error, if there is any.
func (c *FakeDolphinClusters) Create(ctx context.Context, dolphinCluster *v1alpha1.DolphinCluster, opts v1.CreateOptions) (result *v1alpha1.DolphinCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(dolphinclustersResource, dolphinCluster), &v1alpha1.DolphinCluster{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DolphinCluster), err
}

// Update takes the representation of a dolphinCluster and updates it. Returns the server's representation of the dolphinCluster, and an error, if there is any.
func (c *FakeDolphinClusters) Update(ctx context.Context, dolphinCluster *v1alpha1.DolphinCluster, opts v1.UpdateOptions) (result *v1alpha1.DolphinCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(dolphinclustersResource, dolphinCluster), &v1alpha1.DolphinCluster{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DolphinCluster), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDolphinClusters) UpdateStatus(ctx context.Context, dolphinCluster *v1alpha1.DolphinCluster, opts v1.UpdateOptions) (*v1alpha1.DolphinCluster, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(dolphinclustersResource, "status", dolphinCluster), &v1alpha1.DolphinCluster{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DolphinCluster), err
}

// Delete takes name of the dolphinCluster and deletes it. Returns an error if one occurs.
func (c *FakeDolphinClusters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(dolphinclustersResource, name, opts), &v1alpha1.DolphinCluster{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDolphinClusters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(dolphinclustersResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.DolphinClusterList{})
	return err
}

// Patch applies the patch and returns the patched dolphinCluster.
func (c *FakeDolphinClusters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DolphinCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(dolphinclustersResource, name, pt, data, subresources...), &v1alpha1.DolphinCluster{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DolphinCluster), err
}
