/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kubesphere/kubeocean-api/apis/kubeocean/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVirtualClusterSpecifications implements VirtualClusterSpecificationInterface
type FakeVirtualClusterSpecifications struct {
	Fake *FakeKubeoceanV1alpha1
}

var virtualclusterspecificationsResource = schema.GroupVersionResource{Group: "kubeocean.kubesphere.io", Version: "v1alpha1", Resource: "virtualclusterspecifications"}

var virtualclusterspecificationsKind = schema.GroupVersionKind{Group: "kubeocean.kubesphere.io", Version: "v1alpha1", Kind: "VirtualClusterSpecification"}

// Get takes name of the virtualClusterSpecification, and returns the corresponding virtualClusterSpecification object, and an error if there is any.
func (c *FakeVirtualClusterSpecifications) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VirtualClusterSpecification, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(virtualclusterspecificationsResource, name), &v1alpha1.VirtualClusterSpecification{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualClusterSpecification), err
}

// List takes label and field selectors, and returns the list of VirtualClusterSpecifications that match those selectors.
func (c *FakeVirtualClusterSpecifications) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VirtualClusterSpecificationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(virtualclusterspecificationsResource, virtualclusterspecificationsKind, opts), &v1alpha1.VirtualClusterSpecificationList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VirtualClusterSpecificationList{ListMeta: obj.(*v1alpha1.VirtualClusterSpecificationList).ListMeta}
	for _, item := range obj.(*v1alpha1.VirtualClusterSpecificationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested virtualClusterSpecifications.
func (c *FakeVirtualClusterSpecifications) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(virtualclusterspecificationsResource, opts))
}

// Create takes the representation of a virtualClusterSpecification and creates it.  Returns the server's representation of the virtualClusterSpecification, and an error, if there is any.
func (c *FakeVirtualClusterSpecifications) Create(ctx context.Context, virtualClusterSpecification *v1alpha1.VirtualClusterSpecification, opts v1.CreateOptions) (result *v1alpha1.VirtualClusterSpecification, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(virtualclusterspecificationsResource, virtualClusterSpecification), &v1alpha1.VirtualClusterSpecification{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualClusterSpecification), err
}

// Update takes the representation of a virtualClusterSpecification and updates it. Returns the server's representation of the virtualClusterSpecification, and an error, if there is any.
func (c *FakeVirtualClusterSpecifications) Update(ctx context.Context, virtualClusterSpecification *v1alpha1.VirtualClusterSpecification, opts v1.UpdateOptions) (result *v1alpha1.VirtualClusterSpecification, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(virtualclusterspecificationsResource, virtualClusterSpecification), &v1alpha1.VirtualClusterSpecification{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualClusterSpecification), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVirtualClusterSpecifications) UpdateStatus(ctx context.Context, virtualClusterSpecification *v1alpha1.VirtualClusterSpecification, opts v1.UpdateOptions) (*v1alpha1.VirtualClusterSpecification, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(virtualclusterspecificationsResource, "status", virtualClusterSpecification), &v1alpha1.VirtualClusterSpecification{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualClusterSpecification), err
}

// Delete takes name of the virtualClusterSpecification and deletes it. Returns an error if one occurs.
func (c *FakeVirtualClusterSpecifications) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(virtualclusterspecificationsResource, name, opts), &v1alpha1.VirtualClusterSpecification{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVirtualClusterSpecifications) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(virtualclusterspecificationsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.VirtualClusterSpecificationList{})
	return err
}

// Patch applies the patch and returns the patched virtualClusterSpecification.
func (c *FakeVirtualClusterSpecifications) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VirtualClusterSpecification, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(virtualclusterspecificationsResource, name, pt, data, subresources...), &v1alpha1.VirtualClusterSpecification{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualClusterSpecification), err
}
