/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kubesphere/kubeocean-api/apis/kubeocean/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDolphinClusterSpecifications implements DolphinClusterSpecificationInterface
type FakeDolphinClusterSpecifications struct {
	Fake *FakeKubeoceanV1alpha1
}

var dolphinclusterspecificationsResource = schema.GroupVersionResource{Group: "kubeocean.kubesphere.io", Version: "v1alpha1", Resource: "dolphinclusterspecifications"}

var dolphinclusterspecificationsKind = schema.GroupVersionKind{Group: "kubeocean.kubesphere.io", Version: "v1alpha1", Kind: "DolphinClusterSpecification"}

// Get takes name of the dolphinClusterSpecification, and returns the corresponding dolphinClusterSpecification object, and an error if there is any.
func (c *FakeDolphinClusterSpecifications) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DolphinClusterSpecification, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(dolphinclusterspecificationsResource, name), &v1alpha1.DolphinClusterSpecification{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DolphinClusterSpecification), err
}

// List takes label and field selectors, and returns the list of DolphinClusterSpecifications that match those selectors.
func (c *FakeDolphinClusterSpecifications) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DolphinClusterSpecificationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(dolphinclusterspecificationsResource, dolphinclusterspecificationsKind, opts), &v1alpha1.DolphinClusterSpecificationList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DolphinClusterSpecificationList{ListMeta: obj.(*v1alpha1.DolphinClusterSpecificationList).ListMeta}
	for _, item := range obj.(*v1alpha1.DolphinClusterSpecificationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dolphinClusterSpecifications.
func (c *FakeDolphinClusterSpecifications) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(dolphinclusterspecificationsResource, opts))
}

// Create takes the representation of a dolphinClusterSpecification and creates it.  Returns the server's representation of the dolphinClusterSpecification, and an error, if there is any.
func (c *FakeDolphinClusterSpecifications) Create(ctx context.Context, dolphinClusterSpecification *v1alpha1.DolphinClusterSpecification, opts v1.CreateOptions) (result *v1alpha1.DolphinClusterSpecification, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(dolphinclusterspecificationsResource, dolphinClusterSpecification), &v1alpha1.DolphinClusterSpecification{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DolphinClusterSpecification), err
}

// Update takes the representation of a dolphinClusterSpecification and updates it. Returns the server's representation of the dolphinClusterSpecification, and an error, if there is any.
func (c *FakeDolphinClusterSpecifications) Update(ctx context.Context, dolphinClusterSpecification *v1alpha1.DolphinClusterSpecification, opts v1.UpdateOptions) (result *v1alpha1.DolphinClusterSpecification, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(dolphinclusterspecificationsResource, dolphinClusterSpecification), &v1alpha1.DolphinClusterSpecification{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DolphinClusterSpecification), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDolphinClusterSpecifications) UpdateStatus(ctx context.Context, dolphinClusterSpecification *v1alpha1.DolphinClusterSpecification, opts v1.UpdateOptions) (*v1alpha1.DolphinClusterSpecification, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(dolphinclusterspecificationsResource, "status", dolphinClusterSpecification), &v1alpha1.DolphinClusterSpecification{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DolphinClusterSpecification), err
}

// Delete takes name of the dolphinClusterSpecification and deletes it. Returns an error if one occurs.
func (c *FakeDolphinClusterSpecifications) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(dolphinclusterspecificationsResource, name, opts), &v1alpha1.DolphinClusterSpecification{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDolphinClusterSpecifications) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(dolphinclusterspecificationsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.DolphinClusterSpecificationList{})
	return err
}

// Patch applies the patch and returns the patched dolphinClusterSpecification.
func (c *FakeDolphinClusterSpecifications) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DolphinClusterSpecification, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(dolphinclusterspecificationsResource, name, pt, data, subresources...), &v1alpha1.DolphinClusterSpecification{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DolphinClusterSpecification), err
}
