/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kubesphere/kubeocean-api/apis/kubeocean/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDolphinServices implements DolphinServiceInterface
type FakeDolphinServices struct {
	Fake *FakeKubeoceanV1alpha1
}

var dolphinservicesResource = schema.GroupVersionResource{Group: "kubeocean.kubesphere.io", Version: "v1alpha1", Resource: "dolphinservices"}

var dolphinservicesKind = schema.GroupVersionKind{Group: "kubeocean.kubesphere.io", Version: "v1alpha1", Kind: "DolphinService"}

// Get takes name of the dolphinService, and returns the corresponding dolphinService object, and an error if there is any.
func (c *FakeDolphinServices) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DolphinService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(dolphinservicesResource, name), &v1alpha1.DolphinService{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DolphinService), err
}

// List takes label and field selectors, and returns the list of DolphinServices that match those selectors.
func (c *FakeDolphinServices) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DolphinServiceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(dolphinservicesResource, dolphinservicesKind, opts), &v1alpha1.DolphinServiceList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DolphinServiceList{ListMeta: obj.(*v1alpha1.DolphinServiceList).ListMeta}
	for _, item := range obj.(*v1alpha1.DolphinServiceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dolphinServices.
func (c *FakeDolphinServices) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(dolphinservicesResource, opts))
}

// Create takes the representation of a dolphinService and creates it.  Returns the server's representation of the dolphinService, and an error, if there is any.
func (c *FakeDolphinServices) Create(ctx context.Context, dolphinService *v1alpha1.DolphinService, opts v1.CreateOptions) (result *v1alpha1.DolphinService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(dolphinservicesResource, dolphinService), &v1alpha1.DolphinService{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DolphinService), err
}

// Update takes the representation of a dolphinService and updates it. Returns the server's representation of the dolphinService, and an error, if there is any.
func (c *FakeDolphinServices) Update(ctx context.Context, dolphinService *v1alpha1.DolphinService, opts v1.UpdateOptions) (result *v1alpha1.DolphinService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(dolphinservicesResource, dolphinService), &v1alpha1.DolphinService{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DolphinService), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDolphinServices) UpdateStatus(ctx context.Context, dolphinService *v1alpha1.DolphinService, opts v1.UpdateOptions) (*v1alpha1.DolphinService, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(dolphinservicesResource, "status", dolphinService), &v1alpha1.DolphinService{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DolphinService), err
}

// Delete takes name of the dolphinService and deletes it. Returns an error if one occurs.
func (c *FakeDolphinServices) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(dolphinservicesResource, name, opts), &v1alpha1.DolphinService{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDolphinServices) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(dolphinservicesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.DolphinServiceList{})
	return err
}

// Patch applies the patch and returns the patched dolphinService.
func (c *FakeDolphinServices) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DolphinService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(dolphinservicesResource, name, pt, data, subresources...), &v1alpha1.DolphinService{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DolphinService), err
}
