/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kubesphere/kubeocean-api/apis/kubeocean/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKindClusters implements KindClusterInterface
type FakeKindClusters struct {
	Fake *FakeKubeoceanV1alpha1
}

var kindclustersResource = schema.GroupVersionResource{Group: "kubeocean.kubesphere.io", Version: "v1alpha1", Resource: "kindclusters"}

var kindclustersKind = schema.GroupVersionKind{Group: "kubeocean.kubesphere.io", Version: "v1alpha1", Kind: "KindCluster"}

// Get takes name of the kindCluster, and returns the corresponding kindCluster object, and an error if there is any.
func (c *FakeKindClusters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.KindCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(kindclustersResource, name), &v1alpha1.KindCluster{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KindCluster), err
}

// List takes label and field selectors, and returns the list of KindClusters that match those selectors.
func (c *FakeKindClusters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.KindClusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(kindclustersResource, kindclustersKind, opts), &v1alpha1.KindClusterList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.KindClusterList{ListMeta: obj.(*v1alpha1.KindClusterList).ListMeta}
	for _, item := range obj.(*v1alpha1.KindClusterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kindClusters.
func (c *FakeKindClusters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(kindclustersResource, opts))
}

// Create takes the representation of a kindCluster and creates it.  Returns the server's representation of the kindCluster, and an error, if there is any.
func (c *FakeKindClusters) Create(ctx context.Context, kindCluster *v1alpha1.KindCluster, opts v1.CreateOptions) (result *v1alpha1.KindCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(kindclustersResource, kindCluster), &v1alpha1.KindCluster{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KindCluster), err
}

// Update takes the representation of a kindCluster and updates it. Returns the server's representation of the kindCluster, and an error, if there is any.
func (c *FakeKindClusters) Update(ctx context.Context, kindCluster *v1alpha1.KindCluster, opts v1.UpdateOptions) (result *v1alpha1.KindCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(kindclustersResource, kindCluster), &v1alpha1.KindCluster{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KindCluster), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKindClusters) UpdateStatus(ctx context.Context, kindCluster *v1alpha1.KindCluster, opts v1.UpdateOptions) (*v1alpha1.KindCluster, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(kindclustersResource, "status", kindCluster), &v1alpha1.KindCluster{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KindCluster), err
}

// Delete takes name of the kindCluster and deletes it. Returns an error if one occurs.
func (c *FakeKindClusters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(kindclustersResource, name, opts), &v1alpha1.KindCluster{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKindClusters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(kindclustersResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.KindClusterList{})
	return err
}

// Patch applies the patch and returns the patched kindCluster.
func (c *FakeKindClusters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KindCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(kindclustersResource, name, pt, data, subresources...), &v1alpha1.KindCluster{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KindCluster), err
}
