/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v2alpha1

import (
	"context"
	"time"

	v2alpha1 "github.com/kubesphere/kubeocean-api/v2/apis/kubeocean/v2alpha1"
	scheme "github.com/kubesphere/kubeocean-api/v2/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ClusterPoolsGetter has a method to return a ClusterPoolInterface.
// A group's client should implement this interface.
type ClusterPoolsGetter interface {
	ClusterPools() ClusterPoolInterface
}

// ClusterPoolInterface has methods to work with ClusterPool resources.
type ClusterPoolInterface interface {
	Create(ctx context.Context, clusterPool *v2alpha1.ClusterPool, opts v1.CreateOptions) (*v2alpha1.ClusterPool, error)
	Update(ctx context.Context, clusterPool *v2alpha1.ClusterPool, opts v1.UpdateOptions) (*v2alpha1.ClusterPool, error)
	UpdateStatus(ctx context.Context, clusterPool *v2alpha1.ClusterPool, opts v1.UpdateOptions) (*v2alpha1.ClusterPool, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v2alpha1.ClusterPool, error)
	List(ctx context.Context, opts v1.ListOptions) (*v2alpha1.ClusterPoolList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.ClusterPool, err error)
	ClusterPoolExpansion
}

// clusterPools implements ClusterPoolInterface
type clusterPools struct {
	client rest.Interface
}

// newClusterPools returns a ClusterPools
func newClusterPools(c *KubeoceanV2alpha1Client) *clusterPools {
	return &clusterPools{
		client: c.RESTClient(),
	}
}

// Get takes name of the clusterPool, and returns the corresponding clusterPool object, and an error if there is any.
func (c *clusterPools) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2alpha1.ClusterPool, err error) {
	result = &v2alpha1.ClusterPool{}
	err = c.client.Get().
		Resource("clusterpools").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterPools that match those selectors.
func (c *clusterPools) List(ctx context.Context, opts v1.ListOptions) (result *v2alpha1.ClusterPoolList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v2alpha1.ClusterPoolList{}
	err = c.client.Get().
		Resource("clusterpools").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterPools.
func (c *clusterPools) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("clusterpools").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a clusterPool and creates it.  Returns the server's representation of the clusterPool, and an error, if there is any.
func (c *clusterPools) Create(ctx context.Context, clusterPool *v2alpha1.ClusterPool, opts v1.CreateOptions) (result *v2alpha1.ClusterPool, err error) {
	result = &v2alpha1.ClusterPool{}
	err = c.client.Post().
		Resource("clusterpools").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterPool).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a clusterPool and updates it. Returns the server's representation of the clusterPool, and an error, if there is any.
func (c *clusterPools) Update(ctx context.Context, clusterPool *v2alpha1.ClusterPool, opts v1.UpdateOptions) (result *v2alpha1.ClusterPool, err error) {
	result = &v2alpha1.ClusterPool{}
	err = c.client.Put().
		Resource("clusterpools").
		Name(clusterPool.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterPool).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *clusterPools) UpdateStatus(ctx context.Context, clusterPool *v2alpha1.ClusterPool, opts v1.UpdateOptions) (result *v2alpha1.ClusterPool, err error) {
	result = &v2alpha1.ClusterPool{}
	err = c.client.Put().
		Resource("clusterpools").
		Name(clusterPool.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterPool).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the clusterPool and deletes it. Returns an error if one occurs.
func (c *clusterPools) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("clusterpools").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterPools) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("clusterpools").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched clusterPool.
func (c *clusterPools) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.ClusterPool, err error) {
	result = &v2alpha1.ClusterPool{}
	err = c.client.Patch(pt).
		Resource("clusterpools").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
