/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v2alpha1

import (
	"context"
	"time"

	v2alpha1 "github.com/kubesphere/kubeocean-api/v2/apis/kubeocean/v2alpha1"
	scheme "github.com/kubesphere/kubeocean-api/v2/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ExposedServicesGetter has a method to return a ExposedServiceInterface.
// A group's client should implement this interface.
type ExposedServicesGetter interface {
	ExposedServices(namespace string) ExposedServiceInterface
}

// ExposedServiceInterface has methods to work with ExposedService resources.
type ExposedServiceInterface interface {
	Create(ctx context.Context, exposedService *v2alpha1.ExposedService, opts v1.CreateOptions) (*v2alpha1.ExposedService, error)
	Update(ctx context.Context, exposedService *v2alpha1.ExposedService, opts v1.UpdateOptions) (*v2alpha1.ExposedService, error)
	UpdateStatus(ctx context.Context, exposedService *v2alpha1.ExposedService, opts v1.UpdateOptions) (*v2alpha1.ExposedService, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v2alpha1.ExposedService, error)
	List(ctx context.Context, opts v1.ListOptions) (*v2alpha1.ExposedServiceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.ExposedService, err error)
	ExposedServiceExpansion
}

// exposedServices implements ExposedServiceInterface
type exposedServices struct {
	client rest.Interface
	ns     string
}

// newExposedServices returns a ExposedServices
func newExposedServices(c *KubeoceanV2alpha1Client, namespace string) *exposedServices {
	return &exposedServices{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the exposedService, and returns the corresponding exposedService object, and an error if there is any.
func (c *exposedServices) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2alpha1.ExposedService, err error) {
	result = &v2alpha1.ExposedService{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("exposedservices").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ExposedServices that match those selectors.
func (c *exposedServices) List(ctx context.Context, opts v1.ListOptions) (result *v2alpha1.ExposedServiceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v2alpha1.ExposedServiceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("exposedservices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested exposedServices.
func (c *exposedServices) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("exposedservices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a exposedService and creates it.  Returns the server's representation of the exposedService, and an error, if there is any.
func (c *exposedServices) Create(ctx context.Context, exposedService *v2alpha1.ExposedService, opts v1.CreateOptions) (result *v2alpha1.ExposedService, err error) {
	result = &v2alpha1.ExposedService{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("exposedservices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(exposedService).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a exposedService and updates it. Returns the server's representation of the exposedService, and an error, if there is any.
func (c *exposedServices) Update(ctx context.Context, exposedService *v2alpha1.ExposedService, opts v1.UpdateOptions) (result *v2alpha1.ExposedService, err error) {
	result = &v2alpha1.ExposedService{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("exposedservices").
		Name(exposedService.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(exposedService).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *exposedServices) UpdateStatus(ctx context.Context, exposedService *v2alpha1.ExposedService, opts v1.UpdateOptions) (result *v2alpha1.ExposedService, err error) {
	result = &v2alpha1.ExposedService{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("exposedservices").
		Name(exposedService.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(exposedService).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the exposedService and deletes it. Returns an error if one occurs.
func (c *exposedServices) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("exposedservices").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *exposedServices) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("exposedservices").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched exposedService.
func (c *exposedServices) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.ExposedService, err error) {
	result = &v2alpha1.ExposedService{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("exposedservices").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
