/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v2alpha1

import (
	"context"
	"time"

	v2alpha1 "github.com/kubesphere/kubeocean-api/v2/apis/kubeocean/v2alpha1"
	scheme "github.com/kubesphere/kubeocean-api/v2/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// KindClusterPoolsGetter has a method to return a KindClusterPoolInterface.
// A group's client should implement this interface.
type KindClusterPoolsGetter interface {
	KindClusterPools() KindClusterPoolInterface
}

// KindClusterPoolInterface has methods to work with KindClusterPool resources.
type KindClusterPoolInterface interface {
	Create(ctx context.Context, kindClusterPool *v2alpha1.KindClusterPool, opts v1.CreateOptions) (*v2alpha1.KindClusterPool, error)
	Update(ctx context.Context, kindClusterPool *v2alpha1.KindClusterPool, opts v1.UpdateOptions) (*v2alpha1.KindClusterPool, error)
	UpdateStatus(ctx context.Context, kindClusterPool *v2alpha1.KindClusterPool, opts v1.UpdateOptions) (*v2alpha1.KindClusterPool, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v2alpha1.KindClusterPool, error)
	List(ctx context.Context, opts v1.ListOptions) (*v2alpha1.KindClusterPoolList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.KindClusterPool, err error)
	KindClusterPoolExpansion
}

// kindClusterPools implements KindClusterPoolInterface
type kindClusterPools struct {
	client rest.Interface
}

// newKindClusterPools returns a KindClusterPools
func newKindClusterPools(c *KubeoceanV2alpha1Client) *kindClusterPools {
	return &kindClusterPools{
		client: c.RESTClient(),
	}
}

// Get takes name of the kindClusterPool, and returns the corresponding kindClusterPool object, and an error if there is any.
func (c *kindClusterPools) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2alpha1.KindClusterPool, err error) {
	result = &v2alpha1.KindClusterPool{}
	err = c.client.Get().
		Resource("kindclusterpools").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of KindClusterPools that match those selectors.
func (c *kindClusterPools) List(ctx context.Context, opts v1.ListOptions) (result *v2alpha1.KindClusterPoolList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v2alpha1.KindClusterPoolList{}
	err = c.client.Get().
		Resource("kindclusterpools").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested kindClusterPools.
func (c *kindClusterPools) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("kindclusterpools").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a kindClusterPool and creates it.  Returns the server's representation of the kindClusterPool, and an error, if there is any.
func (c *kindClusterPools) Create(ctx context.Context, kindClusterPool *v2alpha1.KindClusterPool, opts v1.CreateOptions) (result *v2alpha1.KindClusterPool, err error) {
	result = &v2alpha1.KindClusterPool{}
	err = c.client.Post().
		Resource("kindclusterpools").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kindClusterPool).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a kindClusterPool and updates it. Returns the server's representation of the kindClusterPool, and an error, if there is any.
func (c *kindClusterPools) Update(ctx context.Context, kindClusterPool *v2alpha1.KindClusterPool, opts v1.UpdateOptions) (result *v2alpha1.KindClusterPool, err error) {
	result = &v2alpha1.KindClusterPool{}
	err = c.client.Put().
		Resource("kindclusterpools").
		Name(kindClusterPool.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kindClusterPool).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *kindClusterPools) UpdateStatus(ctx context.Context, kindClusterPool *v2alpha1.KindClusterPool, opts v1.UpdateOptions) (result *v2alpha1.KindClusterPool, err error) {
	result = &v2alpha1.KindClusterPool{}
	err = c.client.Put().
		Resource("kindclusterpools").
		Name(kindClusterPool.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kindClusterPool).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the kindClusterPool and deletes it. Returns an error if one occurs.
func (c *kindClusterPools) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("kindclusterpools").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *kindClusterPools) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("kindclusterpools").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched kindClusterPool.
func (c *kindClusterPools) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.KindClusterPool, err error) {
	result = &v2alpha1.KindClusterPool{}
	err = c.client.Patch(pt).
		Resource("kindclusterpools").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
