/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"net/http"

	v1beta1 "github.com/kubesphere/kubeocean-api/apis/bootstrap/v1beta1"
	"github.com/kubesphere/kubeocean-api/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type BootstrapV1beta1Interface interface {
	RESTClient() rest.Interface
	KubeadmConfigsGetter
	KubeadmConfigTemplatesGetter
}

// BootstrapV1beta1Client is used to interact with features provided by the bootstrap group.
type BootstrapV1beta1Client struct {
	restClient rest.Interface
}

func (c *BootstrapV1beta1Client) KubeadmConfigs(namespace string) KubeadmConfigInterface {
	return newKubeadmConfigs(c, namespace)
}

func (c *BootstrapV1beta1Client) KubeadmConfigTemplates(namespace string) KubeadmConfigTemplateInterface {
	return newKubeadmConfigTemplates(c, namespace)
}

// NewForConfig creates a new BootstrapV1beta1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*BootstrapV1beta1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new BootstrapV1beta1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*BootstrapV1beta1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &BootstrapV1beta1Client{client}, nil
}

// NewForConfigOrDie creates a new BootstrapV1beta1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *BootstrapV1beta1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new BootstrapV1beta1Client for the given RESTClient.
func New(c rest.Interface) *BootstrapV1beta1Client {
	return &BootstrapV1beta1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1beta1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *BootstrapV1beta1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
