/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v2alpha1

import (
	"context"
	time "time"

	kubeoceanv2alpha1 "github.com/kubesphere/kubeocean-api/v2/apis/kubeocean/v2alpha1"
	versioned "github.com/kubesphere/kubeocean-api/v2/client/clientset/versioned"
	internalinterfaces "github.com/kubesphere/kubeocean-api/v2/client/informers/externalversions/internalinterfaces"
	v2alpha1 "github.com/kubesphere/kubeocean-api/v2/client/listers/kubeocean/v2alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// KindClusterPoolInformer provides access to a shared informer and lister for
// KindClusterPools.
type KindClusterPoolInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v2alpha1.KindClusterPoolLister
}

type kindClusterPoolInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewKindClusterPoolInformer constructs a new informer for KindClusterPool type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewKindClusterPoolInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredKindClusterPoolInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredKindClusterPoolInformer constructs a new informer for KindClusterPool type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredKindClusterPoolInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KubeoceanV2alpha1().KindClusterPools().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KubeoceanV2alpha1().KindClusterPools().Watch(context.TODO(), options)
			},
		},
		&kubeoceanv2alpha1.KindClusterPool{},
		resyncPeriod,
		indexers,
	)
}

func (f *kindClusterPoolInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredKindClusterPoolInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *kindClusterPoolInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&kubeoceanv2alpha1.KindClusterPool{}, f.defaultInformer)
}

func (f *kindClusterPoolInformer) Lister() v2alpha1.KindClusterPoolLister {
	return v2alpha1.NewKindClusterPoolLister(f.Informer().GetIndexer())
}
