/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kubesphere/kubeocean-api/apis/kubeocean/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// DolphinClusterSpecificationLister helps list DolphinClusterSpecifications.
// All objects returned here must be treated as read-only.
type DolphinClusterSpecificationLister interface {
	// List lists all DolphinClusterSpecifications in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.DolphinClusterSpecification, err error)
	// Get retrieves the DolphinClusterSpecification from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.DolphinClusterSpecification, error)
	DolphinClusterSpecificationListerExpansion
}

// dolphinClusterSpecificationLister implements the DolphinClusterSpecificationLister interface.
type dolphinClusterSpecificationLister struct {
	indexer cache.Indexer
}

// NewDolphinClusterSpecificationLister returns a new DolphinClusterSpecificationLister.
func NewDolphinClusterSpecificationLister(indexer cache.Indexer) DolphinClusterSpecificationLister {
	return &dolphinClusterSpecificationLister{indexer: indexer}
}

// List lists all DolphinClusterSpecifications in the indexer.
func (s *dolphinClusterSpecificationLister) List(selector labels.Selector) (ret []*v1alpha1.DolphinClusterSpecification, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.DolphinClusterSpecification))
	})
	return ret, err
}

// Get retrieves the DolphinClusterSpecification from the index for a given name.
func (s *dolphinClusterSpecificationLister) Get(name string) (*v1alpha1.DolphinClusterSpecification, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("dolphinclusterspecification"), name)
	}
	return obj.(*v1alpha1.DolphinClusterSpecification), nil
}
