/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kubesphere/kubeocean-api/apis/kubeocean/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// KindClusterLister helps list KindClusters.
// All objects returned here must be treated as read-only.
type KindClusterLister interface {
	// List lists all KindClusters in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.KindCluster, err error)
	// Get retrieves the KindCluster from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.KindCluster, error)
	KindClusterListerExpansion
}

// kindClusterLister implements the KindClusterLister interface.
type kindClusterLister struct {
	indexer cache.Indexer
}

// NewKindClusterLister returns a new KindClusterLister.
func NewKindClusterLister(indexer cache.Indexer) KindClusterLister {
	return &kindClusterLister{indexer: indexer}
}

// List lists all KindClusters in the indexer.
func (s *kindClusterLister) List(selector labels.Selector) (ret []*v1alpha1.KindCluster, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.KindCluster))
	})
	return ret, err
}

// Get retrieves the KindCluster from the index for a given name.
func (s *kindClusterLister) Get(name string) (*v1alpha1.KindCluster, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("kindcluster"), name)
	}
	return obj.(*v1alpha1.KindCluster), nil
}
