/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/kubesphere/kubeocean-api/apis/kubeocean/v1alpha1"
	scheme "github.com/kubesphere/kubeocean-api/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VirtualClusterSpecificationsGetter has a method to return a VirtualClusterSpecificationInterface.
// A group's client should implement this interface.
type VirtualClusterSpecificationsGetter interface {
	VirtualClusterSpecifications() VirtualClusterSpecificationInterface
}

// VirtualClusterSpecificationInterface has methods to work with VirtualClusterSpecification resources.
type VirtualClusterSpecificationInterface interface {
	Create(ctx context.Context, virtualClusterSpecification *v1alpha1.VirtualClusterSpecification, opts v1.CreateOptions) (*v1alpha1.VirtualClusterSpecification, error)
	Update(ctx context.Context, virtualClusterSpecification *v1alpha1.VirtualClusterSpecification, opts v1.UpdateOptions) (*v1alpha1.VirtualClusterSpecification, error)
	UpdateStatus(ctx context.Context, virtualClusterSpecification *v1alpha1.VirtualClusterSpecification, opts v1.UpdateOptions) (*v1alpha1.VirtualClusterSpecification, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.VirtualClusterSpecification, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.VirtualClusterSpecificationList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VirtualClusterSpecification, err error)
	VirtualClusterSpecificationExpansion
}

// virtualClusterSpecifications implements VirtualClusterSpecificationInterface
type virtualClusterSpecifications struct {
	client rest.Interface
}

// newVirtualClusterSpecifications returns a VirtualClusterSpecifications
func newVirtualClusterSpecifications(c *KubeoceanV1alpha1Client) *virtualClusterSpecifications {
	return &virtualClusterSpecifications{
		client: c.RESTClient(),
	}
}

// Get takes name of the virtualClusterSpecification, and returns the corresponding virtualClusterSpecification object, and an error if there is any.
func (c *virtualClusterSpecifications) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VirtualClusterSpecification, err error) {
	result = &v1alpha1.VirtualClusterSpecification{}
	err = c.client.Get().
		Resource("virtualclusterspecifications").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VirtualClusterSpecifications that match those selectors.
func (c *virtualClusterSpecifications) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VirtualClusterSpecificationList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.VirtualClusterSpecificationList{}
	err = c.client.Get().
		Resource("virtualclusterspecifications").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested virtualClusterSpecifications.
func (c *virtualClusterSpecifications) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("virtualclusterspecifications").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a virtualClusterSpecification and creates it.  Returns the server's representation of the virtualClusterSpecification, and an error, if there is any.
func (c *virtualClusterSpecifications) Create(ctx context.Context, virtualClusterSpecification *v1alpha1.VirtualClusterSpecification, opts v1.CreateOptions) (result *v1alpha1.VirtualClusterSpecification, err error) {
	result = &v1alpha1.VirtualClusterSpecification{}
	err = c.client.Post().
		Resource("virtualclusterspecifications").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(virtualClusterSpecification).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a virtualClusterSpecification and updates it. Returns the server's representation of the virtualClusterSpecification, and an error, if there is any.
func (c *virtualClusterSpecifications) Update(ctx context.Context, virtualClusterSpecification *v1alpha1.VirtualClusterSpecification, opts v1.UpdateOptions) (result *v1alpha1.VirtualClusterSpecification, err error) {
	result = &v1alpha1.VirtualClusterSpecification{}
	err = c.client.Put().
		Resource("virtualclusterspecifications").
		Name(virtualClusterSpecification.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(virtualClusterSpecification).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *virtualClusterSpecifications) UpdateStatus(ctx context.Context, virtualClusterSpecification *v1alpha1.VirtualClusterSpecification, opts v1.UpdateOptions) (result *v1alpha1.VirtualClusterSpecification, err error) {
	result = &v1alpha1.VirtualClusterSpecification{}
	err = c.client.Put().
		Resource("virtualclusterspecifications").
		Name(virtualClusterSpecification.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(virtualClusterSpecification).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the virtualClusterSpecification and deletes it. Returns an error if one occurs.
func (c *virtualClusterSpecifications) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("virtualclusterspecifications").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *virtualClusterSpecifications) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("virtualclusterspecifications").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched virtualClusterSpecification.
func (c *virtualClusterSpecifications) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VirtualClusterSpecification, err error) {
	result = &v1alpha1.VirtualClusterSpecification{}
	err = c.client.Patch(pt).
		Resource("virtualclusterspecifications").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
