/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v2alpha1

import (
	v2alpha1 "github.com/kubesphere/kubeocean-api/v2/apis/kubeocean/v2alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ClusterPoolLister helps list ClusterPools.
// All objects returned here must be treated as read-only.
type ClusterPoolLister interface {
	// List lists all ClusterPools in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v2alpha1.ClusterPool, err error)
	// Get retrieves the ClusterPool from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v2alpha1.ClusterPool, error)
	ClusterPoolListerExpansion
}

// clusterPoolLister implements the ClusterPoolLister interface.
type clusterPoolLister struct {
	indexer cache.Indexer
}

// NewClusterPoolLister returns a new ClusterPoolLister.
func NewClusterPoolLister(indexer cache.Indexer) ClusterPoolLister {
	return &clusterPoolLister{indexer: indexer}
}

// List lists all ClusterPools in the indexer.
func (s *clusterPoolLister) List(selector labels.Selector) (ret []*v2alpha1.ClusterPool, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v2alpha1.ClusterPool))
	})
	return ret, err
}

// Get retrieves the ClusterPool from the index for a given name.
func (s *clusterPoolLister) Get(name string) (*v2alpha1.ClusterPool, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v2alpha1.Resource("clusterpool"), name)
	}
	return obj.(*v2alpha1.ClusterPool), nil
}
